---
year: '2022'
booktitle: NeurIPS 2021 Workshop on Pre-registration in Machine Learning
volume: '181'
shortname: Prereg
start: 2021-12-13
end: 2021-12-13
published: 2022-10-05
layout: proceedings
series: Proceedings of Machine Learning Research
publisher: PMLR
issn: 2640-3498
id: Prereg2022
month: 0
cycles: false
bibtex_editor: Albanie, Samuel and Henriques, Jo\~{a}o F. and Bertinetto, Luca and
  Hern{\'a}ndez-Garc{\'\i}a, Alex and Doughty, Hazel and Varol, G\"{u}l
editor:
- given: Samuel
  family: Albanie
- given: João F.
  family: Henriques
- given: Luca
  family: Bertinetto
- given: Alex
  family: Hernández-Garcı́a
- given: Hazel
  family: Doughty
- given: Gül
  family: Varol
title: Proceedings of Machine Learning Research
description: |
  NeurIPS 2021 Workshop on Pre-registration in Machine Learning
    Held in Virtual on 13 December 2021

  Published as Volume 181 by the Proceedings of Machine Learning Research on 05 October 2022.

  Volume Edited by:
    Samuel Albanie
    João F. Henriques
    Luca Bertinetto
    Alex Hernández-Garcı́a
    Hazel Doughty
    Gül Varol

  Series Editors:
    Neil D. Lawrence
date_str: 13 Dec
url: https://proceedings.mlr.press
author:
  name: PMLR
baseurl: "/v181"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
exclude:
- README.md
- Gemfile
- ".gitignore"
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: mlresearch/jekyll-theme
style: pmlr
permalink: "/:title.html"
ghub:
  edit: true
  repository: v181
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
  comments: false
volume_type: Volume
volume_dir: v181
email: ''
conference:
  name: NeurIPS 2021 Workshop on Pre-registration in Machine Learning
  url: https://preregister.science
  location: Virtual
  dates:
  - 2021-12-13
analytics:
  google:
    tracking_id: UA-92432422-1
orig_bibfile: "/Users/neil/mlresearch/v181/prereg22.bib"
# Site settings
# Original source:  /Users/neil/mlresearch/v181/prereg22.bib
